import { useState, useEffect } from 'react'

const translations = {
  en: {
    instant_legal_help: 'Instant Legal Help',
    language: 'Language',
    emergency_help: '🚨 Emergency Help',
    emergency_description: 'Need urgent legal assistance? Connect with a lawyer within 30 seconds',
    get_help_now: 'Get Help Now',
    voice_help: 'Voice-Based Help',
    voice_description: 'Cannot read? Press the button and speak your problem',
    press_and_speak: 'Press and Speak Your Problem',
    select_your_issue: 'Select Your Legal Issue',
    police_issue: 'Police Issue',
    domestic_violence: 'Domestic Violence',
    property_dispute: 'Property Dispute',
    loan_money: 'Loan/Money Issue',
    labour_issue: 'Labour Issue',
    accident: 'Accident',
    connect_with_lawyer: 'Connect with Legal Expert',
    emergency_connecting: 'Connecting you to an available lawyer immediately...',
    choose_call_type: 'Choose how you want to connect',
    video_call: 'Video Call',
    audio_call: 'Audio Call',
    chat: 'Chat',
    connecting: 'Connecting to lawyer...',
    location_detected: 'Location detected',
    confidential: 'Confidential',
    privacy_protected: 'Your privacy is protected',
    '24_7_available': '24/7 Available',
    always_here: 'We are always here to help',
    expert_lawyers: 'Expert Lawyers',
    qualified_help: 'Qualified legal assistance',
    free_consultation: 'Free Consultation',
    no_hidden_charges: 'No hidden charges',
    footer_text: 'Scan4Legal - Your right to legal help, simplified',
    helpline: 'Helpline',
    select_category_first: 'Please select a legal issue category first',
    voice_error: 'Voice recognition failed. Please try again.',
    voice_not_supported: 'Voice recognition is not supported in your browser.',
    waiting_for_lawyer: 'Waiting for available lawyer...',
    queue_position: 'Queue position',
    estimated_wait: 'Estimated wait',
    minutes: 'minutes',
    cancel: 'Cancel',
    lawyer: 'Lawyer',
    type_message: 'Type your message...',
    call_ended: 'Call Ended',
    call_duration: 'Call duration',
    rate_experience: 'Rate your experience',
    share_feedback: 'Share your feedback (optional)',
    back_to_home: 'Back to Home',
    submit_feedback: 'Submit Feedback',
    connection_failed: 'Connection Failed',
    try_again_later: 'Please try again later',
    try_again: 'Try Again'
  },
  hi: {
    instant_legal_help: 'तत्काल कानूनी सहायता',
    language: 'भाषा',
    emergency_help: '🚨 आपातकालीन सहायता',
    emergency_description: 'तत्काल कानूनी सहायता चाहिए? 30 सेकंड में वकील से जुड़ें',
    get_help_now: 'अभी सहायता पाएं',
    voice_help: 'आवाज़ आधारित सहायता',
    voice_description: 'पढ़ नहीं सकते? बटन दबाएं और अपनी समस्या बोलें',
    press_and_speak: 'बटन दबाकर अपनी समस्या बोलें',
    select_your_issue: 'अपनी कानूनी समस्या चुनें',
    police_issue: 'पुलिस मामला',
    domestic_violence: 'घरेलू हिंसा',
    property_dispute: 'संपत्ति विवाद',
    loan_money: 'ऋण/धन मामला',
    labour_issue: 'श्रम मामला',
    accident: 'दुर्घटना',
    connect_with_lawyer: 'कानूनी विशेषज्ञ से जुड़ें',
    emergency_connecting: 'तुरंत उपलब्ध वकील से जुड़ रहे हैं...',
    choose_call_type: 'कैसे जुड़ना चाहते हैं चुनें',
    video_call: 'वीडियो कॉल',
    audio_call: 'ऑडियो कॉल',
    chat: 'चैट',
    connecting: 'वकील से जुड़ रहे हैं...',
    location_detected: 'स्थान का पता चला',
    confidential: 'गोपनीय',
    privacy_protected: 'आपकी गोपनीया सुरक्षित है',
    '24_7_available': '24/7 उपलब्ध',
    always_here: 'हम हमेशा मदद के लिए हैं',
    expert_lawyers: 'विशेषज्ञ वकील',
    qualified_help: 'योग्य कानूनी सहायता',
    free_consultation: 'मुफ्त परामर्श',
    no_hidden_charges: 'कोई छिपी हुई फीस नहीं',
    footer_text: 'स्कैन4लीगल - आपका कानूनी सहायता का अधिकार, सरल बनाया गया',
    helpline: 'हेल्पलाइन',
    select_category_first: 'कृपया पहले एक कानूनी समस्या श्रेणी चुनें',
    voice_error: 'आवाज़ पहचान विफल। कृपया फिर से कोशिश करें।',
    voice_not_supported: 'आपके ब्राउज़र में आवाज़ पहचान समर्थित नहीं है।'
  },
  bn: {
    instant_legal_help: 'তাত্ক্ষণিক আইনি সাহায্য',
    language: 'ভাষা',
    emergency_help: '🚨 জরুরি সাহায্য',
    emergency_description: 'জরুরি আইনি সহায়তা প্রয়োজন? 30 সেকেন্ডের মধ্যে একজন আইনজীবীর সাথে সংযোগ করুন',
    get_help_now: 'এখনই সাহায্য নিন',
    voice_help: 'ভয়েস-ভিত্তিক সাহায্য',
    voice_description: 'পড়তে পারেন না? বোতাম টিপুন এবং আপনার সমস্যা বলুন',
    press_and_speak: 'বোতাম টিপে আপনার সমস্যা বলুন',
    select_your_issue: 'আপনার আইনি সমস্যা নির্বাচন করুন',
    police_issue: 'পুলিশ মামলা',
    domestic_violence: 'গার্হস্থ্য সহিংসতা',
    property_dispute: 'সম্পত্তি বিবাদ',
    loan_money: 'ঋণ/অর্থ সমস্যা',
    labour_issue: 'শ্রম সমস্যা',
    accident: 'দুর্ঘটনা',
    connect_with_lawyer: 'আইনি বিশেষজ্ঞের সাথে যোগাযোগ করুন',
    emergency_connecting: 'অবিলম্বে একজন উপলব্ধ আইনজীবীর সাথে সংযোগ স্থাপন করা হচ্ছে...',
    choose_call_type: 'কিভাবে যোগাযোগ করতে চান তা নির্বাচন করুন',
    video_call: 'ভিডিও কল',
    audio_call: 'অডিও কল',
    chat: 'চ্যাট',
    connecting: 'আইনজীবীর সাথে সংযোগ স্থাপন করা হচ্ছে...',
    location_detected: 'অবস্থান সনাক্ত হয়েছে',
    confidential: 'গোপনীয়',
    privacy_protected: 'আপনার গোপনীয়তা সুরক্ষিত',
    '24_7_available': '২৪/৭ উপলব্ধ',
    always_here: 'আমরা সবসময় সাহায্যের জন্য আছি',
    expert_lawyers: 'বিশেষজ্ঞ আইনজীবী',
    qualified_help: 'যোগ্য আইনি সহায়তা',
    free_consultation: 'বিনামূল্যে পরামর্শ',
    no_hidden_charges: 'কোন লুকানো চার্জ নেই',
    footer_text: 'স্ক্যান4লিগ্যাল - আপনার আইনি সাহায্যের অধিকার, সহজ করা হয়েছে',
    helpline: 'হেল্পলাইন',
    select_category_first: 'অনুগ্রহ করে প্রথমে একটি আইনি সমস্যা বিভাগ নির্বাচন করুন',
    voice_error: 'ভয়েস সনাক্তকরণ ব্যর্থ হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।',
    voice_not_supported: 'আপনার ব্রাউজারে ভয়েস সনাক্তকরণ সমর্থিত নয়।'
  },
  te: {
    instant_legal_help: 'తక్షణ న్యాయ సహాయం',
    language: 'భాష',
    emergency_help: '🚨 అత్యవసర సహాయం',
    emergency_description: 'తక్షణ న్యాయ సహాయం అవసరం? 30 సెకన్లలో న్యాయవాదితో కనెక్ట్ అవ్వండి',
    get_help_now: 'ఇప్పుడే సహాయం పొందండి',
    voice_help: 'వాయిస్-ఆధారిత సహాయం',
    voice_description: 'చదవలేరా? బటన్ నొక్కి మీ సమస్యను చెప్పండి',
    press_and_speak: 'బటన్ నొక్కి మీ సమస్యను చెప్పండి',
    select_your_issue: 'మీ న్యాయ సమస్యను ఎంచుకోండి',
    police_issue: 'పోలీస్ విషయం',
    domestic_violence: 'గృహ హింస',
    property_dispute: 'ఆస్తి వివాదం',
    loan_money: 'రుణ/డబ్బు సమస్య',
    labour_issue: 'కార్మిక సమస్య',
    accident: 'ప్రమాదం',
    connect_with_lawyer: 'న్యాయ నిపుణుడితో కనెక్ట్ అవ్వండి',
    emergency_connecting: 'వెంటనే అందుబాటులో ఉన్న న్యాయవాదితో కనెక్ట్ అవుతోంది...',
    choose_call_type: 'ఎలా కనెక్ట్ కావాలి ఎంచుకోండి',
    video_call: 'వీడియో కాల్',
    audio_call: 'ఆడియో కాల్',
    chat: 'చాట్',
    connecting: 'న్యాయవాదితో కనెక్ట్ అవుతోంది...',
    location_detected: 'స్థానం గుర్తించబడింది',
    confidential: 'రహస్యం',
    privacy_protected: 'మీ గోప్యత రక్షించబడింది',
    '24_7_available': '24/7 అందుబాటులో ఉంద�',
    always_here: 'మేమందరం సహాయం కోసం ఇక్కడే ఉన్నాము',
    expert_lawyers: 'నిపుణులైన న్యాయవాదులు',
    qualified_help: 'అర్హత గల న్యాయ సహాయం',
    free_consultation: 'ఉచిత సలహా',
    no_hidden_charges: 'దాచిన ఫీజులు లేవు',
    footer_text: 'స్కాన్4లీగల్ - మీ న్యాయ సహాయం హక్కు, సులభం చేయబడింది',
    helpline: 'హెల్ప్‌లైన్',
    select_category_first: 'దయచేసి ముందుగా ఒక న్యాయ సమస్య వర్గాన్ని ఎంచుకోండి',
    voice_error: 'వాయిస్ గుర్తింపు విఫలమైంది. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    voice_not_supported: 'మీ బ్రౌజర్‌లో వాయిస్ గుర్తింపు మద్దతు లేదు.'
  },
  mr: {
    instant_legal_help: 'तात्काळ कायदेशीर मदत',
    language: 'भाषा',
    emergency_help: '🚨 आपत्कालीन मदत',
    emergency_description: 'तात्काळ कायदेशीर मदत हवी आहे? ३० सेकंदात वकीलाशी जुळवा',
    get_help_now: 'आत्ता मदत घ्या',
    voice_help: 'आवाज-आधारित मदत',
    voice_description: 'वाचू शकत नाही? बटण दाबा आणि तुमची समस्या सांगा',
    press_and_speak: 'बटण दाबून तुमची समस्या सांगा',
    select_your_issue: 'तुमची कायदेशीर समस्या निवडा',
    police_issue: 'पोलिस प्रकरण',
    domestic_violence: 'घरगुती हिंसा',
    property_dispute: 'मालमत्ता वाद',
    loan_money: 'कर्ज/पैसे समस्या',
    labour_issue: 'कामगार समस्या',
    accident: 'अपघात',
    connect_with_lawyer: 'कायदेशीर तज्ञांशी जुळवा',
    emergency_connecting: 'तात्काळ उपलब्ध वकीलांशी जुळवत आहे...',
    choose_call_type: 'कसे जुळवायचे ते निवडा',
    video_call: 'व्हिडिओ कॉल',
    audio_call: 'ऑडिओ कॉल',
    chat: 'चॅट',
    connecting: 'वकीलांशी जुळवत आहे...',
    location_detected: 'स्थान ओळखले',
    confidential: 'गोपनीय',
    privacy_protected: 'तुमची गोपनीयता सुरक्षित आहे',
    '24_7_available': '२४/७ उपलब्ध',
    always_here: 'आम्ही नेहमी मदतीसाठी आहोत',
    expert_lawyers: 'तज्ञ वकील',
    qualified_help: 'पात्र कायदेशीर मदत',
    free_consultation: 'विनामूल्य सल्ला',
    no_hidden_charges: 'कोणतेही लपविलेले शुल्क नाही',
    footer_text: 'स्कॅन४लीगल - तुमचा कायदेशीर मदतीचा हक्क, सोपा केला',
    helpline: 'हेल्पलाइन',
    select_category_first: 'कृपया आधी एक कायदेशीर समस्या श्रेणी निवडा',
    voice_error: 'आवाज ओळख अयशस्वी. कृपया पुन्हा प्रयत्न करा.',
    voice_not_supported: 'तुमच्या ब्राउझरमध्ये आवाज ओळख समर्थित नाही.'
  },
  ta: {
    instant_legal_help: 'உடனடி சட்ட உதவி',
    language: 'மொழி',
    emergency_help: '🚨 அவசர உதவி',
    emergency_description: 'உடனடி சட்ட உதவி தேவையா? 30 விநாடிகளில் வழக்கறிஞருடன் இணைக்கவும்',
    get_help_now: 'இப்போது உதவி பெறுங்கள்',
    voice_help: 'குரல் அடிப்படையிலான உதவி',
    voice_description: 'படிக்க முடியாதா? பொத்தானை அழுத்தி உங்கள் பிரச்சனையைச் சொல்லுங்கள்',
    press_and_speak: 'பொத்தானை அழுத்தி உங்கள் பிரச்சனையைச் சொல்லுங்கள்',
    select_your_issue: 'உங்கள் சட்ட பிரச்சனையைத் தேர்ந்தெடுக்கவும்',
    police_issue: 'போலீஸ் விவகாரம்',
    domestic_violence: 'வீட்டு வன்முறை',
    property_dispute: 'சொத்து தகராறு',
    loan_money: 'கடன்/பணம் பிரச்சனை',
    labour_issue: 'தொழிலாளர் பிரச்சனை',
    accident: 'விபத்து',
    connect_with_lawyer: 'சட்ட நிபுணருடன் இணைக்கவும்',
    emergency_connecting: 'உடனடியாக கிடைக்கக்கூடிய வழக்கறிஞருடன் இணைக்கிறது...',
    choose_call_type: 'எப்படி இணைக்க விரும்புகிறீர்கள் என்பதைத் தேர்ந்தெடுக்கவும்',
    video_call: 'வீடியோ அழைப்பு',
    audio_call: 'ஆடியோ அழைப்பு',
    chat: 'அரட்டை',
    connecting: 'வழக்கறிஞருடன் இணைக்கிறது...',
    location_detected: 'இருப்பிடம் கண்டறியப்பட்டது',
    confidential: 'ரகசியமானது',
    privacy_protected: 'உங்கள் தனியுரிமை பாதுகாக்கப்பட்டது',
    '24_7_available': '24/7 கிடைக்கிறது',
    always_here: 'நாங்கள் எப்போதும் உதவிக்கு இங்கே இருக்கிறோம்',
    expert_lawyers: 'நிபுணர்களான வழக்கறிஞர்கள்',
    qualified_help: 'தகுதிவாய்ந்த சட்ட உதவி',
    free_consultation: 'இலவச ஆலோசனை',
    no_hidden_charges: 'மறைக்கப்பட்ட கட்டணங்கள் இல்லை',
    footer_text: 'ஸ்கேன4லீகல் - உங்கள் சட்ட உதவி உரிமை, எளிதாக்கப்பட்டது',
    helpline: 'உதவி வரி',
    select_category_first: 'தயவுசெய்து முதலில் ஒரு சட்ட பிரச்சனை வகையைத் தேர்ந்தெடுக்கவும்',
    voice_error: 'குரல் அடையாளம் தோல்வியடைந்தது. தயவுசெய்து மீண்டும் முயற்சிக்கவும்.',
    voice_not_supported: 'உங்கள் உலாவியில் குரல் அடையாளம் ஆதரிக்கப்படவில்லை.'
  }
}

export function useLanguage() {
  // Initialize language directly from localStorage or browser
  const getInitialLanguage = () => {
    if (typeof window !== 'undefined') {
      const stored = localStorage.getItem('scan4legal-language')
      if (stored && translations[stored as keyof typeof translations]) {
        return stored
      } else {
        const browserLang = navigator.language.split('-')[0]
        if (translations[browserLang as keyof typeof translations]) {
          return browserLang
        }
      }
    }
    return 'en'
  }

  const [language, setLanguageState] = useState(getInitialLanguage)

  const changeLanguage = (lang: string) => {
    setLanguageState(lang)
    if (typeof window !== 'undefined') {
      localStorage.setItem('scan4legal-language', lang)
    }
  }

  const t = (key: string): string => {
    const langTranslations = translations[language as keyof typeof translations]
    return langTranslations?.[key as keyof typeof langTranslations] || key
  }

  return {
    t,
    language,
    setLanguage: changeLanguage
  }
}